apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: git-resolver
  annotations:
    pipelinesascode.tekton.dev/on-event: "[push]"
    pipelinesascode.tekton.dev/on-target-branch: "[main]" 
    pipelinesascode.tekton.dev/task-0: "https://raw.githubusercontent.com/redhat-appstudio/tssc-sample-pipelines/main/pac/tasks/git-clone.yaml"
  labels:
    argocd/app-name: acs-test
    janus-idp.io/tekton: acs-test
    backstage.io/kubernetes-id: acs-test
    backstage.io/kubernetes-namespace: acs-test
    app.kubernetes.io/part-of: acs-test
spec: 
  params:
  - name: message
    value: "Hello"
  pipelineRef:
    name: git-resolver-pipeline
  workspaces: 
    - name: workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
