apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: git-resolver
  annotations:
    pipelinesascode.tekton.dev/on-event: "[push]"
    pipelinesascode.tekton.dev/on-target-branch: "[main]"  
    pipelinesascode.tekton.dev/task-0: ".tekton/print-message.yaml" 
   labels:
    argocd/app-name: acs-test
    janus-idp.io/tekton: acs-test
    backstage.io/kubernetes-id: acs-test
    backstage.io/kubernetes-namespace: acs-test
    app.kubernetes.io/part-of: acs-test
spec: 
  params:
  - name: message
    value: "Hello"
  - name: git-url
    value: "https://github.com/jduimovich/git-resolver"
  pipelineRef: 
    resolver: git
    params:
    - name: url
      value: https://github.com/jduimovich/rhtap-catalog.git
    - name: revision
      value: main
    - name: pathInRepo
      value: pipeline/git-resolver-test/0.1/git-resolver-test.yaml
  workspaces: 
    - name: workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
