apiVersion: tekton.dev/v1
kind: Pipeline
metadata: 
  name: git-resolver-pipeline
spec: 
  params: 
    - default: "default message"
      description: Random Param
      name: message
      type: string 
  tasks:
    - name: git-clone
      params:
        - name: url
          value:  https://github.com/jduimovich/git-resolver
        - name: revision
          value: main
      taskRef:
        name: git-clone  
    - name: print-message
      params:
        - name: message
          value:  "hi mom" 
      taskRef:
        name: print-message
  workspaces:
    - name: output
      workspace: workspace
